### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by StevenWafeek** [Jrmcuervo/RoR-group-project#8]
https://github.com/users/Jrmcuervo/projects/2/views/3
There are 2 members of the team :
- Ruben Cuervo
- Steven wafeek

**Comment by mckent05** [comment]
Hi team, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All tasks have been fairly assigned✔️ ✔️ 
- Your Kanban board has been well set up 👍 👍 


## Required Changes ♻️
- You have done well so far, but there are some tasks that are missing in your Kanban board, and according to the project requirements, all tasks should be represented in your Kanban board:
1.  Food list (**only for a group that has less than 3 members**):
    - Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
    - Should lead to a form that allows users to add new food.
 2. - Make sure there are no N+1 queries happening.
 3. - General shopping list view (**only for a group that has less than 3 members**):
    - Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
    - Should count the total food items and total price of the missing food.
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Jrmcuervo** [comment]
Hello @mckent05  ! Thank you very much for your time and for your feedback, I was re-reading the requirements and I couldn't find where it says that we should add even the cards of activities that will not take place, since we are a group of two, even in the project requirements mention that only if there is a third member in the team. Hopefully, you can point me to which part of the requirements specifically says that we include all the activities. Regarding point number two of your feedback, if you could carefully review the kanban board #5 card, you will see that the activity you mention is included there. Once again, thanks for your time and we look forward to your comments, regards!

**Comment by nicupop729** [comment]
Hello @team 👋,

_This is an additional review as a result of the second opinion request._

Kudos for the great work until now in the programme!

Upon checking what the previous reviewer requested, I noticed an aspect that could have confused you: the Food list and the General Shopping list view are expected to be done by a team of 2 members, not equal or bigger than 3.

![image](https://github.com/Jrmcuervo/RoR-group-project/assets/83596135/ec809478-f8a8-428f-ae66-19f5f0d75a1d)
![image](https://github.com/Jrmcuervo/RoR-group-project/assets/83596135/ae8354bd-7988-4b50-b610-64a827e5bc92)

Please ignore the requirement regarding the N+1 queries, but please add the Food list and the General Shopping list view requirements to the Kanband board with the corresponding cards.

Keep rocking 🚀!

**Comment by DammyShittu** [comment]
Hi @Jrmcuervo and @StevenWafeek,

## APPROVED 🟢

## Highlights
✔️ Assigned tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
